const AUDIT_ACTIONS = {
  USER_REGISTER: 'USER_REGISTER',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGOUT: 'LOGOUT',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  FORBIDDEN_ACCESS: 'FORBIDDEN_ACCESS',
  TAREA_CREATED: 'TAREA_CREATED',
  TAREA_DELETED: 'TAREA_DELETED',
};

module.exports = AUDIT_ACTIONS;
